# Generated by Django 3.1.3 on 2020-12-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('pk_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'photo_db',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('user_email', models.CharField(max_length=200, unique=True)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'user_db',
            },
        ),
    ]
