# Generated by Django 3.1.3 on 2020-12-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_comment_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_posting',
            name='post',
            field=models.CharField(max_length=50),
        ),
    ]
