# Generated by Django 3.1.3 on 2020-12-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_auto_20201130_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='user_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='signup',
            table='user_db',
        ),
    ]
