# Generated by Django 3.1.3 on 2020-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_auto_20201203_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_posting',
            name='post',
            field=models.IntegerField(max_length=50),
        ),
    ]
