# Generated by Django 3.1.3 on 2020-12-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0004_auto_20201203_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_posting',
            options={'ordering': ['created']},
        ),
    ]
