# Generated by Django 3.1.3 on 2020-12-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_auto_20201202_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.TextField(max_length=50),
        ),
    ]
